#!/bin/sh
##############################################################################
# Copyright (c) CERN 2010
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

GLITE_HOME=${GLITE_HOME:-/opt/glite}
export PATH=$PATH:${GLITE_HOME}/libexec
CONFIG=${GLITE_HOME}/etc/glite-info-service-bdii-top.conf
TEMPLATE=${GLITE_HOME}/etc/glite-info-glue2-bdii-top.conf.template
SCRIPT=${GLITE_HOME}/libexec/glite-info-glue2-simple
DEFAULTS=${GLITE_HOME}/etc/glite-info-site-defaults.conf

# Check for the existence of the configuration file.
if [ -f ${DEFAULTS} ]; then
    source ${DEFAULTS}
fi

SITE_NAME=${SITE_NAME:-$(hostname -d) }
BDII_HOST=${SITE_BDII_HOST:-$(hostname -f) }
export BDII_HOST

# Check for the existence of the configuration file.
if [ ! -f ${CONFIG} ]; then

   # Check for the existence of the template.
    if [ ! -f ${TEMPLATE} ]; then
        echo "Error: The template file ${TEMPLATE} does not exist." 1>&2
	exit 1
    else
	${SCRIPT} ${TEMPLATE} ${SITE_NAME}
    fi 
else

${SCRIPT} ${CONFIG} ${SITE_NAME}

fi


