#!/bin/sh
##############################################################################
# Copyright (c) CERN 2010
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

CONFIG=/var/cache/glite/top-urls.conf
SCRIPT=/usr/libexec/glite-info-provider-ldap

# Check for the existence of the configuration file.
if [ ! -f "${CONFIG}" ]; then
	echo "Error: The configuration file ${CONFIG} does not exist." 1>&2
	exit 1
fi

# Check for the existence of the provider.
if [ ! -f "${SCRIPT}" ]; then
	echo "Error: The provider ${SCRIPT} does not exist." 1>&2
	exit 1
fi

${SCRIPT} -c "${CONFIG}" -g grid
